### ISSUE TITLE
NameError: name 'sign' is not defined

### ISSUE THREAD

**Issue by mbondehansen** [fnielsen/lcc-sentiment#1]
When the following code is running:

#### Cross-tabulation of three-class'ed manual and automated scores
C = pd.crosstab(sign(df[indices].valence), sign(df[indices].afinn))
C

I get the above mentioned error: NameError: name 'sign' is not defined. 

If I delete the sign(), I then get the error:
AttributeError: 'DataFrame' object has no attribute 'afinn'

**Comment by fnielsen** [comment]
I am sorry. I am using my "everything" package that is not available from PyPI. I should fix this.
